### ISSUE TITLE
Player animations using weapons

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#100]
Create and implement animations where the character is using weapons. 

Created:
Player Idle using hammer, dagger, and shield
Player attack using hammer, dagger

Future: glaive, sword, ax, spear

**Comment by nsmryan** [comment]
I added the hammer animation and cleaned up animation use a bit. Its not perfect yet, but its better.

Its neat to see the hammer animation play. Looks good.

**Comment by MicroChasm** [comment]
This is discussed elsewhere
