### ISSUE TITLE
Environmental Interaction

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#101]
I think that we need to come up with ways that the player can interact with the environment without making a lot of sound. Basically, I think that if we look at the three stages of the game: exploration, planning, and execution, the planning stage would be a lot more interesting if your plans could involve a little manipulation. Maybe we implement one "power" in the game, which is the ability to move a terrain tile in a direction, or to destroy a terrain tile, or lay a trap.

**Comment by j0e1GMR** [comment]
This also mitigates issues with level design. It's pretty much a universal issue with roguelikes that, since they are procedurally generated, the designer can't account for every possible level. So you get runs like the one I had in Crawl where I died in 77 turns to a shaft trap. But if the player can affect the environment, they can soften that sharp edge a bit.

**Comment by nsmryan** [comment]
We have been adding skills related to execution, but perhaps there could be exploration skills as well.


For example, a way to through an item, such as a light, into an unexplored area, and see it for a turn.
Or a way to move a few turns invisibly, perhaps leaving your body behind, and snapping back when you run out of turns.
Or a way to see through a wall for a turn.

Or just that system of crouching behind walls, or peaking past corners? We could rediscuss those concepts with the new FOV system, where we have more control over things.

**Comment by nsmryan** [comment]
Concepts:
lantern that you pick up and put down. You see FOV of lantern. May need energy to light, may need to throw, may burn out without more energy.

Shade form: leave body (but can still see its FOV). snaps back after a few turns. can snap back by command. will snap if attacked.  monsters can see you.

Vision- choose a wall and can see through as if invisible.


Considering UI of new features in 3D.

**Comment by MicroChasm** [comment]
This concept is discussed elsewhere
