### ISSUE TITLE
Player hearing

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#105]
If the monster sound overlaps the player tile, then the monster sound should be visible, whether or not the player can see those tiles.

**Comment by nsmryan** [comment]
This is implemented. Its a bit hard to test, but trying it out i the TestWall map seems to show it working.

I just realized that I should check that sounds are displayed in two cases (probably):
If the sound overlaps the player, and
If the monster is in FOV.

Do you agree? I am just thinking of the case where a monster walks up to you, and you suddenly see their sound files. It doesn't really make sense that you would see the sound in this case, but it seems clearer for the player.

**Comment by nsmryan** [comment]
Instead, make it so sound only shows up if you can't see the monster.
This makes sound more information, but doesn't clutter the screen when there are multiple monsters. Why would you need the sound if you can see the monster?

**Comment by nsmryan** [comment]
This is implemented now, so sounds only animate if they are caused by the player, or if they are caused by an entity that the player cannot see and the sound overlaps with the player position.

**Comment by MicroChasm** [comment]
This works as best as I can tell.
