### ISSUE TITLE
Monsters Slip Past Player when Push

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#106]
Sometimes when the player pushes a monster into a wall, the player will move correctly but the monster will appear to side-step the push. It's like they slip away when pushed into the wall.

An example would be the player moving two squares up to push a monster into a wall. The player moves two squares, and instead of dying the monster moves one square to the left.

**Comment by nsmryan** [comment]
Does this still happen? With the changes I'm not sure. If so, is there a reproducable situation?

**Comment by nsmryan** [comment]
Given all the changes we have made, I imagine even if a similar issue existed, it would have a different cause.

I think we can probably close this issue and make a new one if we see it, as we will have a log to replicate and fix the problem.
