### ISSUE TITLE
All Monsters and Items in REXPaint

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#110]
Currently there are items spawned in code. Ideally all terrain pieces, items, as well as the goal and exit objects will be painted on in REXPaint.

**Comment by j0e1GMR** [comment]
This includes grass and rubble, which necessitates a new grass tile.

**Comment by nsmryan** [comment]
This should be resolved- i removed the item and grass tile generation.

**Comment by nsmryan** [comment]
Are we good to close this? We don't use rexpaint as much, but if we did and found a problem we can make a new issue.

**Comment by MicroChasm** [comment]
yea, we can close this out for now, I think REXPaint has served its purpose.
