### ISSUE TITLE
Outline

### ISSUE THREAD

**Issue by nsmryan** [nsmryan/RustRoguelike#116]
The story outlines:
Journey between cities/areas
Repetition of three pedestals, with a single statue, gradual reveal a second statue.
Movement towards a mountain/huge tower
meeting with a mysterious person who may be another powerful character
Entrance and path to the center
Meeting with the Vivec character, who has summoned you. he is unable to achieve his own goals, due to a need to keep the tower up which in turn feeds him power. instead he wants you to help establish him as a central ruler.

Themes:
Mysterious past of many cultures
Ruins and collapse of civilizations
Energy sources that permeate technology and probably other things (art, constructions, etc)
Many choices, all of which are wrong in some ways. Balancing and making difficult choices with no way to completely resolve problems.

**Comment by MicroChasm** [comment]
This is continued in the GDD
