### ISSUE TITLE
Hammering Walls

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#118]
When you hammer a full-tile wall, both the tile that the wall occupied as well as the next tile in line with the hit should become filled with rubble, as if the wall fell in that direction. Similarly, you should be able to strike a between-tile wall with the hammer and the tile in the direction of the strike should become full of rubble, and any monster occupying that tile should be destroyed.

**Comment by nsmryan** [comment]
This is implemented now. Not 100% tested (like crushing an enemy behind a short wall), but it looks good to me.

**Comment by nsmryan** [comment]
Walls work, and there is at least some testing for them. I believe this all works now.

**Comment by MicroChasm** [comment]
[issue118.txt](https://github.com/nsmryan/RustRoguelike/files/4985794/issue118.txt)

While hammering walls does work, it only removes the image of one side of the wall.

**Comment by nsmryan** [comment]
This is a strange one. 
For vertical (|) walls, the wall that used to have the between-tile-wall attached leaves its image, and for horizontal walls (_) its the tile below the one that had a between-tile-wall attached.
