### ISSUE TITLE
Monster AI Pathfinding When Idle

### ISSUE THREAD

**Issue by nsmryan** [nsmryan/RustRoguelike#119]
A gol that is attacking the player, and the player moves so they are no longer visible, will move to a different tile then expected when pathfinding in Idle mode.

This creates a weird feeling for the gol ai.

**Comment by nsmryan** [comment]
This seems to be fixed as well- the gols do not stop or move weirdly, at least not in the same way?


One thing we might want to discuss is whether monsters are willing to move out of FOV of the player in order to reach a position to attack. It kind of makes it seems like they are running away, and has a strange feeling.

**Comment by j0e1GMR** [comment]
I don't know if this should be a different issue, but I do still see the monsters walking around until they walk on traps. To replicate, you can switch to sneaking, pick up the dagger, go a little to the right and then up to stab the gol. Then go back around the wall to hide, and continuously pass turns. Pressing "t" helps of course.

**Comment by nsmryan** [comment]
I made the change that monsters do not investigate if they already see the tile that made the sound and it is a monster.

The other changes we might make: 
a cooldown on investigating? that might help settle things down
We could look at whether new noises cause monsters to investigate new things- perhaps there is something going on with them continually changing focus.
We might also make the noise a little less, to alert others less.

**Comment by j0e1GMR** [comment]
For now, we should make it so that monsters do not investigate noise made by other monsters, so that their behavior is more understandable. We can consider adding more investigation back later.

**Comment by MicroChasm** [comment]
I find that the monsters still wander around on their own, and I believe that they still walk onto traps, so that if you pass turns over and over they will eventually kill themselves.

**Comment by nsmryan** [comment]
I commited a change to make it so monsters only investigate the player. They do not seem to have the same wandering behavior as before.
