### ISSUE TITLE
Gol Does Not Follow Sometimes

### ISSUE THREAD

**Issue by nsmryan** [nsmryan/RustRoguelike#122]
Go left until next to gol.
Move right until 1 space between you and gol.
Pass turn.

The gol does nothing- it doesn't seem to know how to path find.

**Comment by nsmryan** [comment]
Okay, this looks fixed to me.

The problem was that pathing allowed the monster to consider the destination of the path to be a valid position to move to, to avoid an issue where the last position was blocked by a target (like the player), and the monsters would believe there was no path to go since they would hit the player.
The fix was to check that the last position is possible to move to without hitting a wall, even if it would hit another entity. This means monsters may walk into each other if the position they are going towards is the same as another  monster. This seems okay- it should only happen if monsters an all investigating a single position, in which case they are already going to walk into each other and pass their turns unable to actually move.

**Comment by j0e1GMR** [comment]
When I attempt this, it actually still appears to happen as before. The Gol stays in place as I pass turns.
In fact, another odd behavior happens, which is visible in the log and if you press "t".  All of the monsters on the board start moving around, but not pathing to the player. If I pass enough turns, they all walk onto traps and die.

**Comment by nsmryan** [comment]
This should be fixed now- they monster was back to thinking that there was no clear path.
