### ISSUE TITLE
Gol Weirdness

### ISSUE THREAD

**Issue by nsmryan** [nsmryan/RustRoguelike#129]
Gols seem to pass their turn, with nothing in the log, sometimes.

This can happen when right next to the player.
This also happened when far away, on a diagonal, and with a column between.

**Comment by nsmryan** [comment]
This should be fixed not- the pathfinding has 1 fewer special case, where the special case was causing the weird behavior.

**Comment by MicroChasm** [comment]
instructions for setting up gol pathing issue:

Z for sneak, L, UL, L, L, DL, D, DL, UL, UL, R, D, D

**Comment by nsmryan** [comment]
Added must_reach to pathing, which indicates whether the move must actually be able to reach the last position.
This may have a problem- its okay to not reach a position due to an entity, but not a wall. 

The new behavior is that the gol gets kind of stuck, and a pawn joins in. They both seem to want to path past each other.

**Comment by nsmryan** [comment]
there is a replay log system now. to see the help use:
cargo run -- --help

**Comment by nsmryan** [comment]
[issue129.txt](https://github.com/nsmryan/RustRoguelike/files/4968864/issue129.txt)
This is the file that recreates the problem:
cargo run -- -r issue129.txt
or
cargo run -- --replay issue129.txt

**Comment by nsmryan** [comment]
I also added a flag for whether to consider traps a blocking entity. I considered generalizing this, but I think its better to leave these two flags until we have more cases to consider.

The pathing should work well now, but check it out just in case.
