### ISSUE TITLE
Hammering Columns

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#132]
Hammering columns exits the game

**Comment by nsmryan** [comment]
Now hammering a column pushes the column over a column.

**Comment by nsmryan** [comment]
The hammer previously assumed that the entity has a 'fighter' field, and crashes if not.

The hammer currently does not emit a Push message, so it is not handling columns separately.

**Comment by nsmryan** [comment]
This seems to work now.

**Comment by MicroChasm** [comment]
[issue132.txt](https://github.com/nsmryan/RustRoguelike/files/4985809/issue132.txt)

Hammering vertically and horizontally seems to work, but on diagonals, the action uses the hammer with no effect.
