### ISSUE TITLE
Monsters Walking into Traps

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#134]
Monsters (Gols at least) will sometimes walk into traps. It seems to have to do with them trying to find their attacking position. 

On Map_2.xp, if you sneak three tiles down and to the left, then wait one turn.

**Comment by nsmryan** [comment]
I don't see this on map 2- is this the correct map to check?

**Comment by nsmryan** [comment]
They should not walk into traps anymore- they should not consider trap tiles viable locations to move.

**Comment by MicroChasm** [comment]
I cannot get them to walk on traps, so I think we can close this. Before it was really noticeable mostly when the golems were walking all around investigating eachother's sounds.
