### ISSUE TITLE
Seeing  full-wall tiles

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#135]
In this case, the player should be able to see the wall. 

![image](https://user-images.githubusercontent.com/4422963/87627979-cd740f80-c6e4-11ea-84ee-3888a70770b3.png)

**Comment by nsmryan** [comment]
It turns out that the reason for this is the between-wall-tile below the player. The check for visibility did not pass through these walls, and it is technically between the player and the square, even though its a bit odd.

I pushed a change that changes this check. Let me know if anything else seems odd before we close the issue.

**Comment by MicroChasm** [comment]
[issue135.txt](https://github.com/nsmryan/RustRoguelike/files/4985628/issue135.txt)

**Comment by nsmryan** [comment]
Suggested algorithm:
To determine if a wall is visible, pathfind up to the tile. If a line can be drawn to the final position from the pathing from the starting position without hitting walls, then the tile is visible.

This seems a little complex, or that it adds a lot of processing- consider caching? Is FOV already cached anywhere?

**Comment by nsmryan** [comment]
I attempted to implement this, but stopped when it became too complex. I will revisit after thinking about it some more.

**Comment by nsmryan** [comment]
Check out light_walls setting- is this aready covered, but stopped by some other logic.

**Comment by nsmryan** [comment]
I think the other FOV changes should help with this. There is still a chance of having artifacts, but this is a similar problem.

**Comment by nsmryan** [comment]
The new FOV algorithm seems to work much better for this.

This should be closable

**Comment by MicroChasm** [comment]
not seeing this wall still seems strange to me

![image](https://user-images.githubusercontent.com/4422963/90855498-a5f01280-e334-11ea-9ea7-a9b66a8e9094.png)

**Comment by nsmryan** [comment]
Is this still an issue? I believe we have adopted the symmetric shadowcasting since this discussion, and I'm not sure whether there are remaining issues.
