### ISSUE TITLE
Shield effect without shield

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#138]
I currently have a hammer and a stone in my inventory, but when I try to switch to run mode, it says that I can't run because I have a shield. This is on map three. I will try to reproduce.

**Comment by j0e1GMR** [comment]
Here is the sequence-- start map 3, and then in sneak mode, pick up the dagger. Then go back and pick up the hammer. You will now not be able to go into run mode.

**Comment by nsmryan** [comment]
The hammer also causes the player to be unable to run, so I think this is expected behavior.

**Comment by nsmryan** [comment]
Fixed message name and printout.
