### ISSUE TITLE
Pawn doesn't follow around corner

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#144]
In some cases, when moving around a corner, the pawn doesn't follow and so loses sight of the player.

**Comment by MicroChasm** [comment]
[issue144.txt](https://github.com/nsmryan/RustRoguelike/files/4976357/issue144.txt)

**Comment by nsmryan** [comment]
I believe the situation is this: the player moves outside of the view of the pawn, and the pawn wants to investigate the player location. However, the player is occupying this location. Therefore, the pawn cannot move, and stays still.

**Comment by MicroChasm** [comment]
That makes sense. My first thought is that there should be a special check for that case, where if the monster finds that the player is occupying a space that they want to occupy, they should attempt to occupy the nearest adjacent space. 

It would also be possible to have them attempt to occupy a space that can see the space that they think that the player is on, but I can see this leading to behavior where they might take a move that is not toward the player, which would seem odd.

**Comment by nsmryan** [comment]
that sounds good. I was thinking about adding a fallback where if they can't reach the square, they try to get it in the FOV.
This does have the problem of possibly having monsters walk away while trying to accomplish this. 

I think a special case makes sense- try to get adjacent such that the square is in your FOV. This should provide reasonable behavior, likely only looking at adjacent squares and not any further.

**Comment by MicroChasm** [comment]
In some circumstances, the golem moves forward to where they could see the player, but does not face the player's position. 
[issue144_2.txt](https://github.com/nsmryan/RustRoguelike/files/4984320/issue144_2.txt)

**Comment by MicroChasm** [comment]
[issue144_3.txt](https://github.com/nsmryan/RustRoguelike/files/4984961/issue144_3.txt)

next actions are: move up, then pass, then upleft

**Comment by nsmryan** [comment]
The entities do not get a chance to change state or facing after their moves, which is part of the problem.

**Comment by nsmryan** [comment]
The entities now can change state at the start and end of each turn.
