### ISSUE TITLE
Monster impressions remain on switching levels

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#146]
After beating one level I started the next level with an impression of a pawn on the screen.

The impressions look so good btw.

**Comment by MicroChasm** [comment]
[issue146.txt](https://github.com/nsmryan/RustRoguelike/files/5012411/issue146.txt)

**Comment by nsmryan** [comment]
Should be fixed- we clear display state between levels now.

**Comment by MicroChasm** [comment]
looks good, I do not see impressions anymore
