### ISSUE TITLE
Panic when pushing a dead enemy

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#148]
thread 'main' panicked at 'Tried to push entity Enemy, alive = false!', roguelike_engine\src\resolve.rs:94:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\roguelike_main.exe` (exit code: 101)

I hit a pawn with a hammer and then moved onto their tile.

**Comment by MicroChasm** [comment]
[issue148.txt](https://github.com/nsmryan/RustRoguelike/files/5013519/issue148.txt)

**Comment by nsmryan** [comment]
The enemy was playing a single frame of animation, which means they were left in the game but marked as alive == false.
I just set killed enemies to blocked = false, and this seems to have fixed it, since they no longer show up as something to push against.
