### ISSUE TITLE
Conversations/Design

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#149]
**Movement System**

jr- we should think about removing the walking state.

**Comment by MicroChasm** [comment]
**Abilities**

Athletic/movement based abilities
Wall-kick
Move two spaces
Wall-kick backwards
Push monster
Push environment piece
Vault environment piece
Do a sweet backflip

Power Arm


Grass

**Comment by MicroChasm** [comment]
**Traps**

What kinds of traps, what do they do?
Trap which takes an action only every other turn
Trap which pushes things outward from a center
Trap which causes an explosion

**Comment by MicroChasm** [comment]
**Classes**

Monolith-- manipulate stone/walls

Grass Mage-- Grass powers

Wind/Fluid/Movement-- open spaces, movement abilities

Clockwork-- gears, power fist

**Comment by MicroChasm** [comment]
**Basic Action**

I think that it might be good to re-examine and finalize the basic actions that you can take in the game.

I've been thinking about roguelike design, and the issue of getting yourself into bad spots. Certain players don't like games where you die 20 moves before your health runs out so to speak. On one hand that's often how roguelikes go, and part of the skill is seeing these situations. However, different roguelikes still handle this better than others. Sil in the early levels, and Descent as well, often see you stuck in spots that are just impossible to do anything about. 
Dungeon Crawl gives you a number of options, especially for mages. The big one is running away. However, most options rely on consumable use, and are a question of matching acceptable loss to the seriousness of the situation. Do you use piety, a scroll of blinking, some wand charges, a potion, etc. There is a current change in the way wands work so that they charge as you gain XP, which makes them more of a strategic question rather than a resource management question. Even though crawl gives you these tools, since they are based on consumables or piety you do not have access to them immediately. 
This is one of the fundamental pillars of the rust roguelike I think, giving players basic but interesting tools to work with. What are all of the current basic tools? Should there be one or two more?

**Comment by nsmryan** [comment]
Lets see if we can state the current set of tools/actions:

## Movement
  * single tile movement
  * blink
  * pass wall
  * Swap position with golem
  * Running movement vs sneaking movement

This can happen from player inputs, traps, and skills.  The player controls movement speed and can choose within a turn.

## Push
  * single tile push

This can happen from a skill currently. I don't think there is any other way to push right now.
I could see a pushing monster as a possibility- they mess up your control over movement. This could also be annoying, but it might not be?
We have also discussed traps that cause a push.

## Wall Manipulation
  * Pass Wall
  * Wall to rubble
  * Rubble to wall
  * Gate trigger raising an lowering wall

This seems like an interesting part of the game, along with pushing. Perhaps we need to explore these a bit more.

## Environment Manipulation
This is similar to wall manipulation, but there are also grass tile skills, and you can disarm and move traps. 

## Item Use
  * Throwing items
  * Using a sword or hammer, or using a dagger implicitly through your movement.


## Overall
It seems like the game is about movement, pushing, and manipulating the elements of the environment. The options are probably not really orthogonal, but that is okay.

There is another core mechanic of stealth and sound that is part of balancing these choices, which is good- I think it might be good to have multiple things on your mind with each choice.

Some thoughts:
  * The pushing aspect is underdeveloped now that the player can't push through movement. Perhaps that would balance the choices out a bit by providing more option through this fairly core mechanic, the way other core mechanics have multiple entry points.
  * The items seem slightly out of character right now. The other aspects of the game are more about the environment, movement, and position, while swords and hammers are a bit direct. Perhaps the hammer should just be a way to push golems or destroy a wall, and maybe only destroy a golem if it pushes them into the wall? This would use pushing more as well. Idk about swords and daggers- maybe they are fine, I don't have any suggestions right now.
  * If the environment had some more variation and ways to interact it might be a bit richer. Especially if those ways of interaction were somehow consistent with wall and grass interactions. To offer some suggestions, perhaps lights would be interesting- they are familiar and interesting visually. Idk about what they might do, except light up areas for the player as we discussed a while back. Perhaps they could repeal golems, or attract them? Or confuse or temporarily disable them? Currently we have walls (monolith class related), and grass (Grass classes related), and perhaps traps are clockwork class related. Perhaps wind, dream, illusion, or some other concept could direct something we add.
  * The base character, as we have discussed, is fairly underpowered. It seems to make sense to have the base character as an athlete, so maybe they should have more movement options as a basic skillset. Maybe only the athlete can vault short walls, or we reintroduce something like climbing walls or wallkicks? I think we are in a position to get these done better with the current state of the code.

**Comment by nsmryan** [comment]
Wind class that uses energy to avoid conflicts, but loses health by doing so. Balances energy use and conflict.

**Comment by nsmryan** [comment]
Some further thoughts:
If the basic interactions are: movement, pushing, and environment interactions (split into wall, trap, trigger, grass, and anything else) we should have a few variations in each, ideally ones that can be combined in some way.
I'll try to think of some variations that might lead to a good set of ideas.

Movement can be:
  * One tile, two, or many
  * Loud or soft
  * Effected by environment or not
  * Controlled or random (like blink)
  * Physical (effected by walls and things), or not (blink/pass wall/switch places, etc). This would include anything like a portal or way-point which involves teleportation. Another idea is a grass type skill were when you stand on grass, all tiles with grass touching the current tile (so the whole patch) is highlighted a bit, and if you use the skill you teleport to a chosen tile on that patch.
  * Athletic or normal- wall jumping for example

We also have the freezing trap, which in a way is a kind of movement mechanic- the frozen golem loses a move. This could be used in skills- like freezing a chosen golem for 1 turn, or freezing a trap so it does not trigger when you step on it (for a few turns, say). Then you could walk over it, and led a golem onto it as a way of handling an encounter.

Pushing:
  * Single tile or multiple, where more then one would be an 'extra powerful' push even at two tiles. This could make some skill particularly useful, but perhaps costly or with limitations.
  * Outwards, inwards, in a chosen direction, or random.
  * Into a blank space, a wall (causing damage), into a trap or trigger. Perhaps short walls do not kill the golems, but destroy the wall, and could do some damage to the golem, as an idea.
I don't know if we have talked about this, but I think pushing should stun a golem- currently pushing them away can cause them to just walk forward on the same turn, which isn't very satisfying.
  * There could also be 'powerful' vs 'weak' pushing, where for example a wind power might push a golem one tile, but could not crush them into a wall, while a power fist requires a close up encounter but can crush them.

Currently all pushing is limited to skills and the hammer item. I wonder what items other items could provide some kind of push as well, like a shield push.

Awareness:
The combined FOV and sound mechanics lead to an 'awareness' kind of play, both for the player trying to gather information, and the golems for detecting the player.

We discussed the 'ethereal form' style skills and lanterns as FOV items. The other idea I had was perhaps an item with a passive effect like you don't make more noise on rubble.

**Comment by MicroChasm** [comment]
Good stuff, we should discuss on a call. I wanted to
