### ISSUE TITLE
Potions

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#15]
We had talked about not having an inventory, in which case we wouldn't do this idea but I wanted to get it down anyway.  I can imagine in a graphical representation of this game the potions could be on a sling, so you could see each one without an inventory screen.

Maybe you choose a layout before the level starts, and you collect them as well.

They could have all sorts of effects:
Get you to max speed in any direction before taking your move
Turn a piece of terrain into a golem
Create a piece of terrain
Call a sandstorm, reduce visibility
Push an enemy back
Teleport you to location
Create a pawn (not ideal but could block LOS)
Create a trap tile
Reduce sound in an area
Create fissure in ground

Then you might make a build like- stealth build with noise/sight reduction and teleport, or board control build with terrain modifiers, or artificer build with golems

**Comment by nsmryan** [comment]
I think we might implement some of these with skills rather then potions. 
What do you want to do with this issue?

**Comment by MicroChasm** [comment]
I am closing the issue because I don't think we should do these with potions anymore. I will add them to a group of ideas about items, probably in the GDD.
