### ISSUE TITLE
Remove Walking

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#151]
For now, the player should only be able to sneak or sprint. Walking made sense in the old system as a transition state, but it seems tedious and puzzly now.

**Comment by nsmryan** [comment]
I removed walking by setting the player to sneak by default, and to make is so you go from sneaking to running, running to sneaking.

This way it is not full removed, but it is no longer accessible.

I don't really feel like i miss is, certainly. I usually just skip between sneaking and running anyway.
