### ISSUE TITLE
Pathing Change

### ISSUE THREAD

**Issue by nsmryan** [nsmryan/RustRoguelike#152]
Pathfinding can switch paths each turn, which causes enemies to behave in a way that it not really intuitive.

Consider keeping the last path, and lowering the cost of performing that path again slightly. This means enemies will slightly prefer to keep an old path.

**Comment by nsmryan** [comment]
This has been changed- monsters attempt to stay in the same direction that they where in last turn. This helps keep them along paths that they were moving along.
This will only work for paths that are actually the same length.

What you do you? I believe this creates the effect we were looking for, in the specific situation we were talking about.

**Comment by MicroChasm** [comment]
I think that this is one that we will have to discuss on a call.

**Comment by nsmryan** [comment]
This should be fixed. Monsters now take into account their orientation and seem to follow paths, such as when you walk around terrain.
