### ISSUE TITLE
You can push a column into a wall

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#154]
I think that it's ok to push a column into a wall... though we may want to discuss. But it currently leaves rubble on the wall tile.

**Comment by MicroChasm** [comment]
[issue154.txt](https://github.com/nsmryan/RustRoguelike/files/5014007/issue154.txt)

**Comment by MicroChasm** [comment]
[MapTestChange.zip](https://github.com/nsmryan/RustRoguelike/files/5014058/MapTestChange.zip)

**Comment by MicroChasm** [comment]
I couldn't get my new map to push to git for some reason, even after resetting the repo and cleaning. The MapTestChange.xp map should be useful for testing pushing columns into walls.

**Comment by nsmryan** [comment]
That map did help.
This is no longer possible- the code checks for blocking objects beyond the column in the direction of the push and suppresses the action if it is invalid (it does not take a turn).
