### ISSUE TITLE
Die on the same turn as beating a level

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#155]
Monsters appear to get a chance to hit you on the turn that you finish a level, making it so that you can die on that turn. If this happens, you start the next level but do not show up on the screen.

**Comment by MicroChasm** [comment]
[issue155.txt](https://github.com/nsmryan/RustRoguelike/files/5032544/issue155.txt)

**Comment by nsmryan** [comment]
I had to check out an older version to get this sequence to play out, but found a version that works.

The game now checks the exit condition before letting enemies move, and will not move them if it is met.
