### ISSUE TITLE
Three-Level Velocity

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#16]
I think its at least worth discussing the idea of a three-level velocity system (so taking three moves in a direction to get top speed).  It wouldn't be necessary to get to top speed too often, but it would reward you to keep your vector in mind when you approach an area.  And then maybe there are ways to manage your velocity, like kicking off a wall while going at velocity 3, and changing your direction but going back down to 2.

At 3 you could take a double-tile move, jump over things, even kick off a wall and go back the other way at a reduced speed. 

It changes the gameplay I feel like-- you end up with the loop of seeing where you need to get (the goal object for instance, or an item), thinking through an approach, trying to execute it, making direction changes on the fly, and then once you are out of the situation you are home free.

**Comment by j0e1GMR** [comment]
Maybe your LOS is increased as you run faster, so you can see farther but enemies can see you sooner.

**Comment by nsmryan** [comment]
Interesting. We might want to visualize the vector in this case, to hint at maintaining it

**Comment by j0e1GMR** [comment]
I'm not 100% on this idea, it might just over-complicate things. If we do add this, it will make the momentum concept more a core feature.

**Comment by nsmryan** [comment]
I think we have moved into a different system with sneaking/running and all. Is there anything to do with this issue?

**Comment by MicroChasm** [comment]
Yea, I think we have moved on from this. If we talk about it again, it will be different enough to open a different issue.
