### ISSUE TITLE
Short Wall System

### ISSUE THREAD

**Issue by nsmryan** [nsmryan/RustRoguelike#165]
Currently short walls block LOS, and block movement except when the player is running.

On the fov_short_walls branch they do not block LOS.

Variations:
  1. Block LOS
  2. Reduce LOS
  3. Block LOS when sneaking. When sneaking an adjacent, FOV extends to the tiles just beyond the wall.
  4. Crouching state where block LOS
  5. If running, don't block LOS

Current concept is to add 3 to fov_short_walls and see if it works out.

**Comment by MicroChasm** [comment]
At work we would call this one OBE: Overcome by Events.
