### ISSUE TITLE
stealth

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#17]
Stealth is tough in roguelikes, and I don't think we really need it, but.., its also pretty cool.

We could have a system where there is a chance that a monster in your LOS notices you, maybe modified by how fast you are running, and if they have direction LOS.

**Comment by nsmryan** [comment]
We have sneaking and direction, and I think that this is our stealth system. There are things we could do to enhance it, like FOV over short walls or crouching near walls or something.

Overall i think we are not making it random, however.

**Comment by nsmryan** [comment]
Issue #273 has more information then this one, and its also about chance based stealth.
I'm closing this issue in favor of the more in depth discussion.
