### ISSUE TITLE
Health

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#18]
This is something that I haven't quite figured out.   It like to not have a traditional 34/50 HP kind of health system. Maybe its just one-hit kill.  Maybe certain monsters just push you back, or you can only push monsters but not kill them. Maybe you need to be checkmated?

**Comment by nsmryan** [comment]
I agree about not using traditional health.

The one hit does make you take thing seriously, although its kind of harsh. We could do a hoplite thing and have a visual indocate of a small number of health.

We can also try a few things to see what works: we probably nees some monster types for testing

**Comment by j0e1GMR** [comment]
I think that having a visual indication of a small amount of health would work yea.  It is an interesting mechanic when health is a resource that you use to solve problems. Into the Breach does this well, where as long as you finish the level you can lose any amount of health, or even one or two mechs.

**Comment by nsmryan** [comment]
We have HP now, and there is a visible indication. It could probably be better, like pips instead of a bar.

What do you think? Is there something to change here, or should we close this issue.
