### ISSUE TITLE
Fov Improvement

### ISSUE THREAD

**Issue by nsmryan** [nsmryan/RustRoguelike#185]
Shadow casting produces better results then my custom FOV.
Using directly, shadow casting is too slow- it is not really intended to be run for each pair of points for each time FOV is needed.

Measure FOV time using python program too see how many FOVs we can afford- if its not many then FOV needs to be optimized.

Once FOV time is acceptable, make map tiles private (with an as_tiles -> &mut function to allow access if needed, or at least make sure all changes go through functions.
Changes invalid FOV cache, and is_in_fov adds to cache.

If this all works, add some kind of new features like fog that affects FOV after algorithm is run by reducing radius allowed.

**Comment by nsmryan** [comment]
This appears to work well.

**Comment by nsmryan** [comment]
This branch is not yet merged - it is called shadowcasting.

**Comment by nsmryan** [comment]
This should be looked over a bit before merging. It appears to be quite nice, but i want to make sure its not losing something.

**Comment by MicroChasm** [comment]
we should discuss on a call to check that the fov is what we want before closing
