### ISSUE TITLE
Pushing Changes

### ISSUE THREAD

**Issue by nsmryan** [nsmryan/RustRoguelike#197]
Consider changes to pushing:

pushing changes: one tile can stun, two tiles can crush, three can crush the thing the push is against.

Consider having pushes (and other movement) occur in stages where each stage resolves before the next.

**Comment by nsmryan** [comment]
Pushing freezes an enemy.
If the enemy is frozen already they become crushed.

**Comment by nsmryan** [comment]
Should pushing stun an enemy always, or only when they hit a wall?
The current game only stuns when hits a wall.

**Comment by MicroChasm** [comment]
Yea, I think it should only be when they hit a wall.

**Comment by MicroChasm** [comment]
OBE
