### ISSUE TITLE
Hold Spacebar

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#213]
It would be a nice feature if, when the player moves their cursor out towards a square and then holds down the spacebar, the move action would be applied at the rate of a tick per some amount of time, maybe half a second. That way, if the player wants to move to a space that is some tiles away, they can take quick moves without pressing the spacebar over and over.

**Comment by nsmryan** [comment]
What about other keys? I could see something like moving the cursor itself, or moving the player with ctrl and a direction.
We could do this for all keys, although some things might not make sense.


I added this, and it seems to work well, but we should discuss.

**Comment by MicroChasm** [comment]
Yea, I definitely think that we should come up with a list of things that you should be able to hold and get a tick of actions. 

We will need to come up with a good delay time that is not so fast that it encourages players to make mistakes. I might open up jupiter hell again to see how they handle it, since they do something along these lines.

**Comment by nsmryan** [comment]
This is currently implemented. The delay is controlled in config.yaml by delay_rate.

Currently this works with most actions. The only one that is excluded is showing the overlay, which would create a weird blinking of information.
Are there other places or ways that we want this to work?

**Comment by nsmryan** [comment]
This is now suppressed for menus.

This issue will remain open until entering and exiting cursor mode also does not get effected by held keys.
