### ISSUE TITLE
Cursor movement direction

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#224]
When using the cursor to choose your direction, the only way to move down currently is if your cursor is directly beneath your character. The only way to move right is if the cursor is directly to the right. Anything in between goes diagonally down and to the right. It would be nice if the directions were more evenly distributed, with a few tiles corresponding to each direction of movement.

**Comment by nsmryan** [comment]
The current implementation just draws a line to the target position, so anything off target ends up moving diagonally for the first tile.
We could do something else as long as we can formalize what we want it to do.

**Comment by MicroChasm** [comment]
![CursorSelection](https://user-images.githubusercontent.com/4422963/108805954-3c57f780-7555-11eb-8b7b-5731538a1468.jpg)

**Comment by MicroChasm** [comment]
the image is not definitive, but I think that it gives some context to start a discussion.

**Comment by nsmryan** [comment]
Is this still relevant? I can't remember if there is actually a way to move the character in cursor mode, or whether it is only for selections/actions.
