### ISSUE TITLE
Impressions When Heard Sound

### ISSUE THREAD

**Issue by nsmryan** [nsmryan/RustRoguelike#228]
There is some commented out code that would draw an "impression" (the grayed out enemy sprite) for enemies that made a sound that the player can hear, but where the enemy themselves is not in FOV.

Did we remove this intentionally, or should I try to add it back in? It seems to make some sense, but I could see an argument that you just use the sound, not the impression, to tell where they are.

**Comment by MicroChasm** [comment]
I believe that we want to keep this in. Since you can see monster noise anyway, it makes sense to show where the monster was without the player having to try to tell from the noise animation. Also, I think its a cool idea.

**Comment by nsmryan** [comment]
The HeardSomething effect might need to add to impressions instead, and then remove the effect?

**Comment by nsmryan** [comment]
Impressions are now added, and the HeardFrom effect removed.
