### ISSUE TITLE
Review Input System Possibilities

### ISSUE THREAD

**Issue by nsmryan** [nsmryan/RustRoguelike#234]
Create a way to test out how SDL2 reacts to inputs.

Discuss current system. Is it awkward? Are we being limited by technical problems, or perhaps just perceived technical problems?

**Comment by MicroChasm** [comment]
Here is a proposed system that we can talk about:

Numpad directions for walking
Shift-direction for run
Ctrl-direction for sneak
Letter-direction uses item in that direction

Press space to enter cursor mode
Shift-direction moves cursor three tiles in a direction
Ctrl-direction moves cursor two tiles away from player in relative positions
Hold letter+space applies that item to that square
Q or Esc exits cursor mode

**Comment by nsmryan** [comment]
Stance is not effected by last move- check whether move mode is updated.
alt + direction needs to perform interaction
alt + direction in cursor mode does not snap to objects (likely needs some discussion)
holding space + direction keys
item + direction does not apply item in that direction

the item concept is not implemented- there is just the primary, secondary, and skills

Dropping items is not implemented
picking up items is not implemented
throw item on player should become a drop not a throw

**Comment by nsmryan** [comment]
This is on the input_revisit branch

**Comment by nsmryan** [comment]
Is there any need for the item selection menu any more? I was looking at removing some of the selection system (where you enter a selection mode and click on a tile), and I realized that this is the only place where the item menu is really used.

**Comment by MicroChasm** [comment]
I think we can nix the item selection menu yea, the new system should supersede it.

**Comment by nsmryan** [comment]
Character shadow should be removed- it doesn't make much sense with this system.
