### ISSUE TITLE
New Tiles/Shadows

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#239]
In order to implement new tiles, we will have to remove the current tile colorization code. We will also have to do some careful layering.

Shadows: Full-tile walls and inter-tile walls will have shadows associated with them. It will help to fix the issue of inter-tile walls currently not communicating their height.

There will be a specific shadow shape for horizontal and vertical inter-tile and full-tile walls. The walls will be render on the top layer, then the top of sprites and any glowing/light pixels, then shadows, then another other sprites. Shadows will be at a transparency.

We could do the glow thing by checking against a mask, which could be packed in the alpha channel.

**Comment by nsmryan** [comment]
Is the new tile set added to the repo? I could try this out a bit and see how much work it is to remove colorizing sprites.

**Comment by MicroChasm** [comment]
I just pushed it, it is called rustrogueliketiles.png. Seems to make sense to move away from the rexpaint name.

**Comment by nsmryan** [comment]
I made an attempt at adding shadows in the 'tiles' branch.
I'm not sure that I did this correctly- lets look it over some time.

**Comment by MicroChasm** [comment]
![RustRoguelikeLevelTest](https://user-images.githubusercontent.com/4422963/120264169-1461e980-c252-11eb-94a9-8276a59d1217.jpg)

**Comment by nsmryan** [comment]
I made some progress on this. However, something is wrong with intertile walls, and I'm having a hard time figuring out what it is.

**Comment by MicroChasm** [comment]
![image](https://user-images.githubusercontent.com/4422963/124875416-b9709000-df7d-11eb-9130-cd6fa9f0b0b4.png)

**Comment by MicroChasm** [comment]
![image](https://user-images.githubusercontent.com/4422963/124875653-018fb280-df7e-11eb-827f-3977170d44bd.png)

Here you can see that the grass tile is displayed on top of the shadow from the full-tile wall. The shadows from the inter-tile walls seem to be layered correctly with the grass.

**Comment by MicroChasm** [comment]
![image](https://user-images.githubusercontent.com/4422963/124875948-559a9700-df7e-11eb-8560-77887297b0e2.png)

Here are some more layering changes to make.

**Comment by MicroChasm** [comment]
![RR_TilesPerspectivetest](https://user-images.githubusercontent.com/4422963/125030599-349a7a80-e040-11eb-9573-2dc6e913dc10.jpg)

Here is a test of 8-directional player and golem tiles.

**Comment by nsmryan** [comment]
I'll take a look at the layering part when I get a chance.

The directional sprites look really good. I have to say its very neat to see them, as if the 2d version was really a flattened version of the 3d.
This makes their facing FoV much more intuitive.

**Comment by nsmryan** [comment]
This is better now, but not perfect. There is some issue with the intertile walls. I can't tell if its me or the tiles themselves.

**Comment by MicroChasm** [comment]
Issues with this system are now being called out individually instead of on this thread.
