### ISSUE TITLE
Lantern Lit Tile FOV

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#266]
The player should be able to see tiles lit by the lantern, but only if the view to the lit tile is not blocked.

**Comment by nsmryan** [comment]
Try this out:
pos in fov is it is fov with the current radius, or it is illuminated and in FOV with infinite radius.

Illumination may need some updates to make this work, such as making it a tile property?

**Comment by nsmryan** [comment]
Is it okay to collect all illuminated tiles each time, even with recursion?

**Comment by nsmryan** [comment]
This is now working. There may be some issues with short walls- I haven't tested these situations.

**Comment by nsmryan** [comment]
Consider a flicking visual, or orange or yellow color?
