### ISSUE TITLE
Golems can Attack when Crouched over Short Wall

### ISSUE THREAD

**Issue by nsmryan** [nsmryan/RustRoguelike#267]

**Comment by nsmryan** [comment]
Is this still true? I did a test with a gol using 'cargo run -- -m test_wall' and it wasn't able to attack over the wall.
This is tied into the ranged vs melee attack idea, but I didn't see the specific behavior of getting attached when crouched over a short wall.

**Comment by MicroChasm** [comment]
I believe that this is fixed.  We can re-open if it comes back up. From what I saw, the golems pathed to me instead of firing over the wall.
