### ISSUE TITLE
Directional Animations

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#278]
I've marked this as a conversation for now, while we decide if we are going this path, and how to go about it.  I've started doing these animations for the player as a test.

**Comment by MicroChasm** [comment]
![PlayerIdleDirectional](https://user-images.githubusercontent.com/4422963/123535949-56a90a00-d6dc-11eb-8706-7226f0642c69.png)

**Comment by nsmryan** [comment]
I have started to get this integrated.
One thing I noticed was that I think we need a separate up and down animation? Those two don't seem like they are just reflections of each other. Right now I don't think we have down animations.

**Comment by nsmryan** [comment]
The current code is on the 'display_refactor' branch.

**Comment by MicroChasm** [comment]
The up and down animations are a little different-- up shows more of the shawl, while down has the shawl open in the middle and has a flesh color for the head, though its hard to tell.  I wonder if I should do something like move the up animation higher in the tile to differentiate it. 

The naming convention is confusing because what used to be called just "Gol_Idle.png" is now used for the down animation. 
I left the naming the way it is because down is sort of the default, but we can always change it.

**Comment by nsmryan** [comment]
I changed the naming convention to match names used in the code, so I can look up the sprite by constructing their name ('player' or 'gol', etc), their stance ('crouching', 'standing', 'running'), and then the direction (up, left, right, down, downleft, downright, upleft, upright).
I also fixed the issue with upleft and downleft animations.
