### ISSUE TITLE
Rooks

### ISSUE THREAD

**Issue by nsmryan** [nsmryan/RustRoguelike#281]
Currently we do not have a rook generated in the procgen system.

It seems like we should add some additional golems for variety, but it seems like the rook should be a bit different from the others.
Perhaps it can has restricted movement, or it can only push you and not attack.

**Comment by MicroChasm** [comment]
Rook acts similar to a Pan, but attacks horizontally and vertically.

**Comment by nsmryan** [comment]
I added an initial version of Rooks just to have them in the game. They move and attack only horizontally and vertically by 1 tile.
