### ISSUE TITLE
Torches

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#29]
It would be cool to have torches on the map which reveal nearby tiles without fog of war.  We have a torch icon already.

**Comment by nsmryan** [comment]
I think this would be fairly straightforward.
One way to do it would be to add a tile type for torches, and draw the torch icon when displaying it.
Then we would need a little code to either set the visibility, or check for nearby torches when deciding on visibility.

**Comment by nsmryan** [comment]
Do we still want to do this? 

I'm not sure it is all too easy- the idea of FOV may be tied into other concepts. Perhaps this is purely a rendering thing, where you check for visibility by the player or visibility from a torch when displaying a tile.

**Comment by MicroChasm** [comment]
we should think about this again, since we are considering an item that extends LOS

**Comment by nsmryan** [comment]
We discussed torches that allow the player to see areas that aren't in FOV.

**Comment by nsmryan** [comment]
Torches are in the game. They illuminate spaces which allows you to see them from further off.
