### ISSUE TITLE
Visualize Golem attacks

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#291]
I would like to see the golem attacks be visualized with a beam, so that it is clear how they are attacking. There are currently sprites on the sheet to use for testing, at positions 196, 199. Ideally in the future we would have some sort of animation for it.

![image](https://user-images.githubusercontent.com/4422963/125132586-61d73f00-e0b9-11eb-9e88-9bdaea95076a.png)

**Comment by nsmryan** [comment]
Try out the initial implementation. I only used the middle two sprites, and rotated them. 
The duration of the beam is controllable with beam_duration in the config.yaml file.
