### ISSUE TITLE
Directional Arrow

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#293]
Currently the directional arrow uses one icon, and rotates it to point in the correct direction. I would like to use two types of arrows instead-- one for vertical and horizontal and one for diagonals. The vertical/horizontal would be position 17 and the diagonal would be position 18 on the tileset.

**Comment by nsmryan** [comment]
Try out the master branch.

**Comment by nsmryan** [comment]
Should we just remove the directional arrow once directional animations are complete? We discussed doing this, and I think its likely the right thing to do.
I added a configuration option called "draw_directional_arrow" and set it to false by default. The game looks cleaner without it, although it does make it very clear which direction everyone is facing. It might still be useful for the information overlay.
