### ISSUE TITLE
Display Layer Issues

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#317]
The player is drawn on top of inter-tile walls. 

Ideally, the player would display on top of the lower half of an inter-tile wall (so that the player's head is on top), and the player would be displayed beneath the upper part of the inter-tile wall (so that the player's feet are beneath).

**Comment by nsmryan** [comment]
This should be fixed on the master branch.
The rendering of intertile walls is now split into two functions so they can be called in different places, allowing them to occur in different layers.

**Comment by MicroChasm** [comment]
spears display on top of inter-tile walls

items display on top of shadows.

**Comment by MicroChasm** [comment]
While most of the issues have been fixed, it is still the case that the leftmost side of up/down inter-tile walls is displayed underneath a shadow.

**Comment by MicroChasm** [comment]
The shadow issue was related to the layout of the sprites. Any additional issues will be addressed individually now.
