### ISSUE TITLE
Grass tile/gate trigger

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#318]
It is possible for gate triggers and grass to spawn on the same tile. Potentially the trigger could be drawn on top of the grass, but I feel like maybe trigger tiles should just remove anything else on the tile when they spawn.

**Comment by nsmryan** [comment]
The render order had triggers under the map for some reason, so I swapped the order.
I can remove grass when triggers spawn, but you could always place down grass such as with the grass throw skill.
Should we always ensure no grass is on trigger tiles, or just on spawn? I could see either way- the trigger may not really be something that grass can grow on, but then what about rubble?

**Comment by MicroChasm** [comment]
I'm trying to figure out what the most interesting course of action is here. Is it more interesting that there are some tiles that you cannot cover in grass, or is it more interesting to be able to do things like step on a trigger tile without making much sound?  I could see, from a practical standpoint, either that the grass can't grow on the trigger tile, or that it grows in the cracks and crevices, and that is enough to count as a soft tile.

The question of grass on rubble is also sort of interesting. Would it just cancel out and that tile would act like a normal tile? 

After going through the options, I am leaning slightly towards allowing grass to be spawned on trigger and rubble tiles, just for the sake of allowing players their fun if that is what they want to do.

**Comment by nsmryan** [comment]
I will make sure that trigger tiles do not spawn with grass on them.

**Comment by nsmryan** [comment]
Triggers and traps now both clear the tile they are created on.
