### ISSUE TITLE
Throwing Stones

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#322]
Throwing stones by pressing C on a tile in Cursor mode doesn't work. Did we change something and I am forgetting, or is this a bug?

**Comment by nsmryan** [comment]
Stones are still thrown in the old way, like items. You have to be in cursor mode, hold alt, and then press the item key for the stone. This is 'z' if you only have a stone, not a fixed 'ammo' or 'consumable' selection.
