### ISSUE TITLE
Changes to Trigger Plates

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#329]
Trigger plates will have a directionality and will be pointed at the wall or walls that they affect.

The affected walls will have a unique tile, different than regular walls. 

If you move the cursor over a trigger, then the affected wall will highlight red.

**Comment by MicroChasm** [comment]
Maybe in the future, we will come back to this and add triggers for inter-tile walls, and have situation where triggers affect a string of wall tiles.

**Comment by nsmryan** [comment]
The original idea here is done. Maybe we can add the intertile wall concept to some "ideas" section like the GDD and close this issue.
