### ISSUE TITLE
Re-Structure Levels

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#33]
I think that we have enough mechanics in the game for it to be run through, but they aren't collected in such a way that you have a fun experience running through the level. I think it might be worth spending some time tweaking level generation, monster attacks, monster generation, things like that, until the level can be run through and the experience is more like a real game.

**Comment by nsmryan** [comment]
One thing we could try is to design a single level that can be played. If this is easier then generating levels, we might be able to keep the layout constant and try to make something playable, and they try to generate random playable levels after that.

**Comment by j0e1GMR** [comment]
I like this idea

**Comment by nsmryan** [comment]
The branch feature_map_files correctly orients maps in a text editor now.
I am thinking that maybe the best way to edit the map is in the game itself. I was going to restructure the key handling to allow input modes. I'm thinking of mapping the key/mouse input into an enum, and then processing the enum in a function.
Then the game state can keep an input state enum, and use that to decide which function to use to process a key input.

**Comment by nsmryan** [comment]
I think the main idea of this thread is something we are still discussing, but it might be good to create a separate issue focused on creating a playable game.
