### ISSUE TITLE
Should Eating Herbs Take a Turn?

### ISSUE THREAD

**Issue by nsmryan** [nsmryan/RustRoguelike#369]
Similar question about stone skin.
I was just looking over some code and noticed that some skills were not using the player's turn, perhaps on purpose, and in some cases by accident.

**Comment by MicroChasm** [comment]
I think it should probably take a turn, yea. I'm not against the idea of adding free actions, like we do with picking things up, but since using other items takes a turn, eating an herb should likely also take a turn.

**Comment by nsmryan** [comment]
Sounds good to me. The change is already made.
