### ISSUE TITLE
Should Stepping on Tall Grass Remove it?

### ISSUE THREAD

**Issue by nsmryan** [nsmryan/RustRoguelike#370]
Looking at tall grass tiles I noticed that it is not clear what to do when the player is within the tile.

One option is for them to hide in the tile, another would be to turn it into short grass. 

Currently it becomes short grass. The way FOV works, I don't think you can hide in it right now- you are visible because usually the player's own tile does not contribute to line of sight (you are never within something that blocks LoS normally), but we could look at changing that.

**Comment by MicroChasm** [comment]
While I kind of like the idea of hiding in tall grass, I think that it might feel a little silly. Turning it to short grass seems fine, like you are trampling it a bit. I'm open to other arguments though.

**Comment by nsmryan** [comment]
I'm good with this answer. It is easier to implement and seem reasonable.
