### ISSUE TITLE
Smoke Bomb Sprite

### ISSUE THREAD

**Issue by nsmryan** [nsmryan/RustRoguelike#383]
The smoke bomb needs a sprite.
Currently it is invisible.

**Comment by MicroChasm** [comment]
smoke tile added, row 8, column 15

**Comment by nsmryan** [comment]
I think row 8 column 15 is smoke, but we still need a smoke bomb itself.

**Comment by MicroChasm** [comment]
oh my bad. Smoke bomb tile added at row 8, column 13
