### ISSUE TITLE
Player sprite after attacking

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#406]
After attacking, specifically with the spear, the "golem impression" sprite is overlaid on top of the player sprite for one turn, until the player does something.

**Comment by nsmryan** [comment]
This was a weird one, but easy to find.

What happens is that attacking creates some sound. The spear is the only weapon where the sound can hit the player from a distance. The sound comes from the player, but does not originate from the player's position, so the player saw this as a sound propagating to them.
If the tile was the player position, this was not caught. 

The change is that impressions can no longer come from the player.

**Comment by nsmryan** [comment]
Are there any other player sprite issues with attacking?
