### ISSUE TITLE
Momentum Scaling/Clinging to High Walls

### ISSUE THREAD

**Issue by nsmryan** [nsmryan/RustRoguelike#41]
With enough momentum, the player should be able to run into a high wall and enter a clinging state.
Then they can kick off the wall, moving an extra tile, or scale the wall to get to the other side.
There could also be a way to get on top of the wall, or drop down.

**Comment by nsmryan** [comment]
This is tied into the momentum system. Do we want to consider concepts like this still, or just close this issue?

**Comment by MicroChasm** [comment]
Sigh. I really like the clinging idea. I'm not sure if it is practical, but it might be worth keeping in mind for an athletic class. I think for now I will move this idea to the design doc and close this issue.
