### ISSUE TITLE
Change state by passing turn

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#413]
Currently, you can only change your state by moving. You should be able to change your state by passing your turn with the new state active.

**Comment by nsmryan** [comment]
There are two different concepts here: stance and move mode.
Pressing shift or ctrl set you move mode to run/sneak/walk.
Moving with a particular move mode sets your stance: Crouch/Standing/Running.

It is supposed to be the case that setting your move mode to run or walk when crouching, then pass your turn, you stand up.

I can see how this is not really intuitive though.

**Comment by nsmryan** [comment]
Try this again and see if it is what you expect.

**Comment by MicroChasm** [comment]
Currently everything works, as far as I can see, except passing a turn into sneak mode. It should be that if you are currently in walking or running mode, you should be able to hold ctrl and press 5 to pass your turn and also switch to sneak mode.

**Comment by nsmryan** [comment]
The sneak+pass turn problem is tracked in https://github.com/nsmryan/RustRoguelike/issues/455, so I think we can close this issue.
