### ISSUE TITLE
Golem spawns trapped

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#415]
In the image below you can see that the golems has spawned in a tile surrounded by walls. Ideally this would not happen. 

![golem spawn](https://user-images.githubusercontent.com/4422963/157380252-af7bc607-9918-4fc8-af09-489d67eefa23.PNG)

**Comment by nsmryan** [comment]
Yea, there is currently nothing to prevent this.

One option is to ensure a path from each golem to the player to ensure that none of them are fully blocked off.

**Comment by nsmryan** [comment]
I added this into the level generation.

**Comment by nsmryan** [comment]
There is always a clear path from golems to the player now.

**Comment by MicroChasm** [comment]
This is tough to check, but I generated lots of levels and never saw this situation again.
