### ISSUE TITLE
Movement key press and hold

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#425]
I hate to go back this, but after playtesting for a while, I think its worth attempting the hold-shift and hold-ctrl style again.

It requires you to hold buttons, which seems like bad design, but our levels are so small that you never have to hold for long.

The idea is easier to communicate and removes the swapping of state during the turn— instead the state swap happens as the turn occurs.

**Comment by nsmryan** [comment]
I made the change- luckily it was straightforward. I also left in the old code commented out just in case.

I think this change makes sense. It is easy enough to press the modifier before moving, and the mental model is easier to keep in your head.
Lets try it out for a while and see if we want to keep the change.

**Comment by MicroChasm** [comment]
I am re-opening this issue because I realized that shift-run doesn't seem to work. ctrl-sneak seems fine though.

**Comment by nsmryan** [comment]
Try to press num lock first and try again

**Comment by MicroChasm** [comment]
yup, you are right. I think I knew this, but since we were changing the keys I thought it was an actual issue this time.
