### ISSUE TITLE
Restart

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#429]
Currently, the restart option in the pause menu causes the level to reset-- I think it would be more useful for playtesting if it reset the player's health, energy, and class as well.

**Comment by nsmryan** [comment]
I made some progress here- restarting now resets hp, energy, and skills.
I noticed that it does not suppress some messages that should be suppressed on the start of a level. The main.rs file handles this, but it is not done on new levels.

**Comment by nsmryan** [comment]
Display messages are now cleared each time a level is started.
