### ISSUE TITLE
Revert from Test Mode

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#445]
Currently, reverting from test mode (the mode that you get into by pressing "t", I don't remember if it has another name) by pressing t again doesn't revert your energy or life in the UI. I believe that it does still revert them in the code, since you can still die.

**Comment by nsmryan** [comment]
I redid test mode so that you keep your hp and energy, but you never lose them.

This seems to keep things a little cleaner visually, since you pips no longer go off the screen.

**Comment by MicroChasm** [comment]
When you revert from test mode you can still see the whole board for a turn, but I don't think that this is really a big deal. The actual issue was solved so this works well now.
