### ISSUE TITLE
Skill Energy Use

### ISSUE THREAD

**Issue by nsmryan** [nsmryan/RustRoguelike#446]
If the player uses a skill within their class, sometimes their energy use is specific to the class. For example the Grass class can use grass to power a skill.
If the player had an ability that is general, or one that is outside of their class, should they still be able to use class based energy use?

At least in the case of wind skills, which use no energy, their other skills should use energy.

Other then that, it seems like it could go either way. I am inclined to think that the energy use mechanism should be per-skill rather then per-class, so any character that uses a grass skill can use grass to power that skill.

**Comment by nsmryan** [comment]
I made the change so that skills use their class instead of the player class, as it seems to make more sense to me.

**Comment by MicroChasm** [comment]
I agree with everything stated here-- the resource use should be per-skill, not per-class.
