### ISSUE TITLE
Esc Key to Quit

### ISSUE THREAD

**Issue by nsmryan** [nsmryan/RustRoguelike#447]
We talked about using the esc key to quit the game, but I don't see an issue for it.

Esc exits cursor mode if it is enabled, but if not then esc brings up the quit menu. Pressing esc again closes the quit menu.

**Comment by nsmryan** [comment]
One thing I noticed while using this- it seems like we should make 'q' not bring up the quit menu any more.
That way we can use 'qwe' for abilities later on when we implement them. I am pretty used to pressing 'q' to quit, but I can get used to this not working.

Agreed?

**Comment by MicroChasm** [comment]
Agreed. There is nothing wrong with q to quit, but esc is standard.

**Comment by MicroChasm** [comment]
I am changing this issue to a cleanup type issue instead of making a new one, just to keep the conversation together. The menu should be switched from "q" to esc.

**Comment by nsmryan** [comment]
I pushed this change.

One question about this: currently the inventory menu no longer really makes sense. It just shows you the buttons on the bottom of the screen (the menu is just a copy of that panel).
It seems like we should just get rid of the idea of an inventory screen, since you can always see your inventory clearly.
Is there any reason we might keep it? A more detailed description of items, or something else we might want?

**Comment by MicroChasm** [comment]
I could see getting rid of it to simplify things, but I think there might still be value in providing a way for players to learn about their items. Ideally, there would be a little image when you have your weapon selected that shows how you can attack with it. In practice, you can find this out pretty quickly on the map. 

However, if we start implementing more complex items, like an artifact that solidifies sandstorms into a glass sphere that you can throw or something like that, then there should really be an item description somewhere.

**Comment by MicroChasm** [comment]
yup, I will make an issue.
