### ISSUE TITLE
Cannot pass turn in sneak mode

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#455]
you currently cannot pass a turn with ctrl pressed. This is true independent of the mode you were in for the previous move.

**Comment by nsmryan** [comment]
This is because pressing 5 with ctrl current causes an "interaction" with the current tile.
This seems like the wrong behavior, but I will have to think about it a bit.

**Comment by nsmryan** [comment]
Thinking about it, interactions don't even work this way anymore- they are done in use-mode, not with ctrl.
This is now fixed and the changed has been pushed.
