### ISSUE TITLE
Swift Message Log

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#458]
When using Swift, you need to start and end without walls adjacent (if I remember correctly). Currently, if you attempt to use Swift but fail because you don't meet the wall requirements, you still get the message "player moves swiftly to ___".

**Comment by nsmryan** [comment]
Should be fixed now.

**Comment by MicroChasm** [comment]
Technically, I think it should probably say "The player failed to move swiftly. The player moves to ___"  but I'm not too worried about this sort of nicety yet.
