### ISSUE TITLE
Potential Momentum Systems

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#46]
1. The tiles that you can move to are always highlighted.  You can move one tile in any direction.  Once you move in a direction, you can move two tiles in that direction or a direction one offset (NW or NE for a move N). Potentially, once you move twice in a direction you can move maybe three tiles in that direction but can't move at all backwards, and would have to stay still for a turn before turning around.

2. You can switch between states- running, sneaking, and regular. In the running states you can move multiple tiles in a direction, and more if you moved in that direction last turn.

3. You have a stamina meter that builds up as you do athletic things.  They could be running in a direction by some mechanism, doing a wall jump, lunging over a wall, things like that, and then when the meter is full, they do a Sweet Athletic Move, like vaulting a high wall, jumping back off a column or tall wall, doing a slide tackle, or possibly tackling or pushing or attacking a monster. 

4. Once you move in a direction, if you want to move in that same direction the next turn, you have to move two tiles, and maybe three tiles in the subsequent turn.  

5. Another one?

**Comment by nsmryan** [comment]
Potential to show momentum with movement of player, or other visual cues.

**Comment by nsmryan** [comment]
Current plan is normal movement is 1 tile.

Modifier key gets you athletic movements. 

Potentially different modifiers for different movements styles (fast vs slow).

Holding shift lets you move two tiles, but makes more noise.
