### ISSUE TITLE
Crash on Restart

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#460]
I got a crash on restarting the game. Here is the crash message and action log:

thread 'main' panicked at 'Component not found for entity!: 0', C:\msys64\home\joelg\RustRoguelikeTiles\roguelike_utils\src\comp.rs:51:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\rl.exe` (exit code: 101)

[action_log.txt](https://github.com/nsmryan/RustRoguelike/files/8736962/action_log.txt)

**Comment by nsmryan** [comment]
Did you pull any changes before the crash happened?

**Comment by MicroChasm** [comment]
I belive that I pulled at the beginning of the play session but there were no changes.

**Comment by nsmryan** [comment]
I believe that I have fixed this one. It was related to vault placement, and removing entities from the wrong structure.
