### ISSUE TITLE
Pick Up/Drop made turn pass

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#462]
I picked up a weapon while currently holding a weapon, and it caused me to pass a turn. If I remember correctly, I think both dropping and picking up are supposed to be free actions. 

[action_log.txt](https://github.com/nsmryan/RustRoguelike/files/8748729/action_log.txt)

**Comment by nsmryan** [comment]
You are correct - I checked the GDD and dropping items should not take a turn. Picking up the item caused you to drop your current item, which was taking a turn.
I fixed this and pushed the change.
