### ISSUE TITLE
Columns spawned outside of level area

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#473]
It looks like this column vault was spawned near the edge of the level and the columns overflowed out beyond the level boundaries. 

![image](https://user-images.githubusercontent.com/4422963/170848652-4d232ccd-62a1-42a9-a879-5bd7309f70f2.png)

https://drive.google.com/file/d/1ZruzCh4d0cYLd0SMXKbiCSO0ueNjRWcF/view?usp=sharing

**Comment by nsmryan** [comment]
This should be fixed. One aspect was a visual glitch with entities marked for removal (because they are out of the bounds of the level), but which were still in the display system.
