### ISSUE TITLE
Use Mode Visual

### ISSUE THREAD

**Issue by nsmryan** [nsmryan/RustRoguelike#474]
Currently when you enter use-mode, you see an arrow for each direction you can choose.

However, you only see the highlight for the result of pressing that direction if you hold it down, so if you want to know all the locations you might hit, you have to hold down each direction. The hit locations are predictable, so this isn't that big of a deal, but we could highlight all positions that are hit by at least one chose of direction.
For current weapons this is pretty readable, since the hit positions don't overlap, and if they do you just have to hold down directions to see which tiles correspond to which direction.

The main thing here is that I can't remember whether we decided to do things this way, or whether its just implemented this way.

**Comment by MicroChasm** [comment]
I feel that this was implemented on purpose, but I think it might work better if the tiles that can be hit are all highlighted. Then, when the button is pressed, only the tiles that will be hit are highlighted, as we have it now.

**Comment by MicroChasm** [comment]
I do like the way that this looks better. The sword is the weapon that suffers the most from the change, but I think that it is acceptable.
