### ISSUE TITLE
Make Atlas causing some issues

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#479]
When I make changes to the sprite sheet and then use the make atlas feature, I get some visual errors. I wonder if the text file is not being updated correctly with tile and animation locations?

![image](https://user-images.githubusercontent.com/4422963/171088013-91aa13cc-5f80-409b-bdd7-7828302dd10b.png)

**Comment by nsmryan** [comment]
Try removing your game.save file. This is likely using old sprite locations because the display state is restored from that file.

**Comment by nsmryan** [comment]
I pushed a change where the atlas file is reloaded even if we have a saved game file.
