### ISSUE TITLE
Tile images are distorted slightly

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#480]
I feel like we might have mentioned this in the past at some point, but the tiles are distorted slightly, making them not appear correct in the game. It makes it difficult to control how the game looks. I think it has to do with the scaling, since the game is larger than the tileset.

**Comment by nsmryan** [comment]
Is there a particular difference I could use as an example to try different scaling levels?
Something like on a trap or other static sprite would be easiest to test with.

**Comment by MicroChasm** [comment]
Here is an example-- the trigger mechanism tile. The left shows the original tile, then in the middle is a correctly scaled version, and then on the right is the version in the game. I think it has to do with interpolating the size-- I get a similar result if I scale the tile up one extra pixel. Maybe it needs to be scaled in a multiple of 16, if it isn't already?

![Tilescaling](https://user-images.githubusercontent.com/4422963/171562840-136382e7-b327-4f9d-8c4c-077f180defd6.png)

**Comment by nsmryan** [comment]
I pushed a commit that displays everything 16 times enlarged, which seems to work.

**Comment by nsmryan** [comment]
I was looking into making the map different dimensions, and I found that the tiles are not exactly equal sized anymore.

I think we should come up with a desired breakout for the screen- how much is UI and how much map, and come up with map dimensions, and then screen dimensions that match this.

**Comment by nsmryan** [comment]
I was looking into the layout of the screen, making the map different dimensions, and why the tiles are distorted, and I believe I have solved the underlying problem now.
Remember to remove your game.save file when you pull the latest master though.

The textures where not being used completely, so the tiles drawn on them where not aligned perfectly. Things should look much better now.
