### ISSUE TITLE
See over short wall

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#60]
When standing, the player should be able to see over the short, in-between walls. When sneaking, the player cannot see over these walls.

**Comment by nsmryan** [comment]
This might be good to implement as a 'height' where the player becomes short when sneaking, and medium when running/walking.

This might help later with different enemy types. It might also be more complex then necessary.

**Comment by nsmryan** [comment]
This is tied in to #156 which will give us the control to do this.

**Comment by MicroChasm** [comment]
This is a good point. The map won't be very interesting if there isn't much to block LOS. I wanted to have a bigger difference between running and sneaking, but maybe we can do that in other ways.

**Comment by nsmryan** [comment]
This is now implemented such that short walls block movement, with the exception of running, and slightly block FOV. You can see over them when standing but only a little when crouching.

The problem I see is that monsters can see you (they always stand), even if you are crouching.

**Comment by MicroChasm** [comment]
I think that originally I had thought that monsters would just not see you when you are crouching behind a short wall, even though theoretically you would be able to see a crouching golem in the same situation (when you are standing). I think it’s ok if there is a discrepancy between the players and golems abilities, but at the same time I want to keep LOS symmetrical. Still, this is one possible solution.

I see two other possible solutions as well. The first is that short walls block sight for tiles directly beyond them even when standing. We could adjust the height of these walls so that this feels like it makes sense.

The second idea is that you can see the tiles beyond short walls, but you still can’t see the player crouching in these tiles. This would make sense if the visuals show the player moving close to the short wall, like they are sneaking. In a Gears of War sort of way if that makes sense.

**Comment by MicroChasm** [comment]
The idea of height is mentioned in this thread, it’s something that we might want to pursue, or at least keep in mind. Abilities and even golem attacks could take place at low, medium, or tall height. Short abilities could be blocked by short walls, and medium abilities by full-tile walls. It would be a way to pack some more information into the board. It might not be a great idea, but it would be possible to have attacks which lob, which might create interesting interactions.

Its also something that Isaac does, though it isn’t explored that much. The Pluto item in repentance does make you too short for a lot of bullet attacks to hit you.

**Comment by nsmryan** [comment]
I made a chang today, on a branch that does the second idea: golems can see tiles over the wall, but not the player in those tiles.
It would work the other way as well, although golems never crouch. Idk that it would make sense to a player or not.
I do think height is interesting as a mechanic

**Comment by MicroChasm** [comment]
We could have golems that crouch, although if the player isn’t visible because they are purposely stealthy then it wouldn’t make much sense for the golem. Probably something we will have to discuss.

**Comment by nsmryan** [comment]
The current situation is as described above: crouching limits the player's FOV over short walls, but also protects against golems seeing you over short walls.
This should work for crouching golems, but they never decide to crouch right now.

This can be used to lose an attacking golem by crouching around an intertile wall, and getting far enough away or hidden before they reach the last position that they saw you standing in.

**Comment by MicroChasm** [comment]
this is implemented as desired
