### ISSUE TITLE
Energy System

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#62]
There should be a state where the player can use their energy tokens. They will have options to do cool things like move further, make silent moves, etc. Maybe even select multiple actions at once, like double silent move. 

The player starts with enough energy to do a good number of things, maybe 12. They get more energy by destroying monsters and picking up vials?

**Comment by nsmryan** [comment]
There is currently an energy system which only decreases when using skills.

There is no way to increase energy right now. I think some kind of item to pick up makes sense.

**Comment by nsmryan** [comment]
Monsters drop an energy circle which you can pick up to increase energy.
