### ISSUE TITLE
Movement modes and sneak attacks

### ISSUE THREAD

**Issue by j0e1GMR** [nsmryan/RustRoguelike#68]
When using the dagger, you should be able to sneak attack any monster that is not aware of you. You can do this dagger attack in sneaking, walking, or running mode. In addition to the noise that you make by moving, the attack itself will make noise emanating from the monster tile location. An attack made in sneaking mode will only make 1 tile of noise, but an attack made in running mode will make a larger noise.

**Comment by nsmryan** [comment]
Are we done with this? You can stab with the dagger, and it does make a sound. I don't think the stab itself makes a sound, which it could if we still want it to.

**Comment by j0e1GMR** [comment]
yea, now that I think about it, the stab itself shouldn't make a sound.
