### ISSUE TITLE
Drop Items

### ISSUE THREAD

**Issue by j0e1GMR** [nsmryan/RustRoguelike#71]
It should be possible to drop items. Dropping an item doesn't take a turn, doesn't make noise, and the item will be on the player's tile. If the player drops more than one item, the second item will be placed at a random (?) adjacent tile. 

Items should be drop through the inventory menu. Since the current functionality is to select the item and then click to throw it, perhaps if you click on your own tile it will drop the item instead.

**Comment by nsmryan** [comment]
If there are no tiles around you, where does the item go? Do we find the closest open tile or something?

**Comment by j0e1GMR** [comment]
The usual solution for this that I've seen is just to find the closest nearby tile, even if it doesn't make logical sense. In some cases, the item is just destroyed if there is no viable tile, but that seems harsh. Another alternative is that you get a message and are not allowed to drop it. My initial thought is the first option-- the closest viable tile, ideally one that is in view if possible.

**Comment by nsmryan** [comment]
This is implemented. It will search up to 10 tiles away using floodfill, and if it fails there is a message in the log.
