### ISSUE TITLE
Info Mode

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#72]
Player attack tiles should be indicated in a different color than the monster attack tiles. Maybe purple.

Perhaps the player can see which tiles an individual monster can see. Perhaps by drawing an arrow from the monster to the center of each tile that they can see.

**Comment by nsmryan** [comment]
Moving the cursor over a golem does show which tiles are visible to the golem, and will show a copy of the golem in every time that they can attach.
