### ISSUE TITLE
Pushing monsters to edge of map

### ISSUE THREAD

**Issue by j0e1GMR** [nsmryan/RustRoguelike#74]
If the player attempts to push a monster against the edge of the map, nothing should happen.

**Comment by nsmryan** [comment]
These tiles are marked as "Water" tiles. This will have to be checked calculate_move in order to prevent it from being a turn.

**Comment by nsmryan** [comment]
Added a check for this finally. Pushing a monster, where the next tile is water, doesn't do anything and doesn't take a turn.
