### ISSUE TITLE
Full keyboard support

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#79]
Every action should be achievable using the keyboard, without the mouse.

**Comment by nsmryan** [comment]
Currently I believe the mouse-only interactions are:
Selection mode
Getting information on tiles


The second is a little harder- maybe there should be a key you press to go into info mode, and you can move the cursor around and see information on the selected tile?

**Comment by nsmryan** [comment]
With the cursor, we can use this as the "selection mode".
I added this to the master branch- if the mouse is not on the screen, then the cursor is used for determining what to show in the information panel.

You can already select tiles with the cursor for things like throwing, so this makes the game fully mouse-free if you choose to play that way.

**Comment by nsmryan** [comment]
There is no mouse use anymore, with the new cursor mode.

I'm closing this as the game is fully keyboard based. We may reintroduce the mouse, but in a different issue.
