### ISSUE TITLE
Items

### ISSUE THREAD

**Issue by j0e1GMR** [nsmryan/RustRoguelike#81]
Spear
 Spears can be thrown to anywhere within LOS and make a noise of 5 tiles. If thrown at a monster they push the enemy back one tile. If the monster is pushed into a wall, the monster is destroyed. Spears can also be used to lunge forward and attack two tiles away, pushing a monster back with a chance to destroy them outright and a chance to break the spear as well.

Sword
Swords can be thrown 4 tiles within LOS, and make a noise of 5 tiles. They can be used to attack all adjacent monsters at once. Monsters are always destroyed, and the sword has a chance to break.

Hammer
Hammers are used to attack an adjacent tile, destroying a monster or wall tile. When the hammer destroys a wall tile, it acts like a pushed column-- the wall is destroyed and a rubble tile is created at the adjacent tile opposite the player. When attacking a monster, the monster is first pushed back before being destroyed, meaning that another monster may be destroyed if it is hit by the first. The hammer has a chance to be broken when it is used to hit either a monster or a wall. The player cannot run while wielding a hammer.

Dagger
Can be thrown to a location within LOS to make noise of 5 tiles. Can be used to attack an adjacent monster. If used to attack an unaware monster, the monster will be destroyed, and the dagger will break. 

Shield
Can be used to block attacks by monsters. When blocking an attack the player will be pushed back one tile, and the shield has a chance to be broken. Can’t run while holding a shield (potentially we could have large and small shields with slightly different rules here). The player is not damaged if pushed into a wall, they simply don't move from their current tile.

**Comment by nsmryan** [comment]
I believe this is cover in the game design document- shall we close this issue and track it there instead?
