### ISSUE TITLE
Gols view distance

### ISSUE THREAD

**Issue by j0e1GMR** [nsmryan/RustRoguelike#95]
Gols seem to have a view distance of five tiles. I am not sure if this is intended. I have not tested if this is also true of elfs.

**Comment by nsmryan** [comment]
All monsters use the same FOV radius now.
It seems like if different monsters have different radii then there should be a visual indicator- otherwise its confusing.

**Comment by nsmryan** [comment]
Use fov_radius_monster to set the monster field radius. If its needs to be per monster, we can add more config items

**Comment by nsmryan** [comment]
@j0e1GMR i think its not clear to me whether there is something to change here
